config/routes.rb
Smartstudent::Application.routes.draw do		
  root :to => "home#index"
  
  get "home/index"

  match 'home' => 'home#index', :as => :home	
  match 'register' => 'users#new',           :as => :register
  match 'login' => 'user_sessions#new',      :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions

  resources :sections do
    resources :smart_reviews do
      resources :course_reviews
      resources :professor_reviews
    end
  end

  resources :courses do
    collection do
      post :search
    end
  end

  resources :departments

  resources :professors do
    collection do
      post :search
    end
  end

  resources :users

end

app/controllers/course_reviews_controller.rb
class CourseReviewsController < ApplicationController
  before_filter :login_required

  # GET /course_reviews
  # GET /course_reviews.xml
  def index
    @course_reviews = CourseReview.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @course_reviews }
    end
  end

  # GET /course_reviews/1
  # GET /course_reviews/1.xml
  def show
    @course_review = CourseReview.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course_review }
    end
  end

  # GET /course_reviews/new
  # GET /course_reviews/new.xml
  def new
    @course_review = CourseReview.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course_review }
    end
  end

  # GET /course_reviews/1/edit
  def edit
    @course_review = CourseReview.find(params[:id])
  end

  # POST /course_reviews
  # POST /course_reviews.xml
  def create
    @course_review = CourseReview.new(params[:course_review])

    respond_to do |format|
      if @course_review.save
        format.html { redirect_to(@course_review, :notice => 'Course review was successfully created.') }
        format.xml  { render :xml => @course_review, :status => :created, :location => @course_review }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course_review.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /course_reviews/1
  # PUT /course_reviews/1.xml
  def update
    @course_review = CourseReview.find(params[:id])

    respond_to do |format|
      if @course_review.update_attributes(params[:course_review])
        format.html { redirect_to(@course_review, :notice => 'Course review was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course_review.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /course_reviews/1
  # DELETE /course_reviews/1.xml
  def destroy
    @course_review = CourseReview.find(params[:id])
    @course_review.destroy

    respond_to do |format|
      format.html { redirect_to(course_reviews_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/course_reviews_helper.rb
module CourseReviewsHelper
end

app/views/course_reviews/_form.html.erb
<%= form_for(@course_review) do |f| %>
  <% if @course_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_review.errors.count, "error") %> prohibited this course_review from being saved:</h2>

      <ul>
      <% @course_review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br />
    <%= f.text_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :usefulness %><br />
    <%= f.text_field :usefulness %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :time_spent %><br />
    <%= f.text_field :time_spent %>
  </div>
  <div class="field">
    <%= f.label :recommend %><br />
    <%= f.text_field :recommend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_reviews/edit.html.erb
<h1>Editing course_review</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_review %> |
<%= link_to 'Back', course_reviews_path %>

app/views/course_reviews/index.html.erb
<h1>Listing course_reviews</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Difficulty</th>
    <th>Usefulness</th>
    <th>Content</th>
    <th>Time spent</th>
    <th>Recommend</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @course_reviews.each do |course_review| %>
  <tr>
    <td><%= course_review.comment %></td>
    <td><%= course_review.difficulty %></td>
    <td><%= course_review.usefulness %></td>
    <td><%= course_review.content %></td>
    <td><%= course_review.time_spent %></td>
    <td><%= course_review.recommend %></td>
    <td><%= link_to 'Show', course_review %></td>
    <td><%= link_to 'Edit', edit_course_review_path(course_review) %></td>
    <td><%= link_to 'Destroy', course_review, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course review', new_course_review_path %>

app/views/course_reviews/new.html.erb
<h1>New course_review</h1>

<%= render 'form' %>

<%= link_to 'Back', course_reviews_path %>

app/views/course_reviews/show.html.erb
<div>
  <b style="display:inline-table">
    Comment:
  </b>
  <span style="display: inline-table">
    <%= course_review.comment %>
  </span>
  <b style="display:inline-table">
    Difficulty:
  </b>
  <span style="display: inline-table">
    <%= course_review.difficulty %>
  </span>
  <b style="display:inline-table">
    Usefulness:
  </b>
  <span style="display: inline-table">
    <%= course_review.usefulness %>
  </span>
  <b style="display:inline-table">
    Content:
  </b>
  <span style="display: inline-table">
    <%= course_review.content %>
  </span>
  <b style="display:inline-table">
    Recommend:
  </b>
  <span style="display: inline-table">
    <%= course_review.recommend %>
  </span>
  <b style="display:inline-table">
    Time spent:
  </b>
  <span style="display: inline-table">
    <%= course_review.time_spent %>
  </span>
</div>


<%= link_to 'Edit', edit_course_review_path(@course_review) %> |
<%= link_to 'Back', course_reviews_path %>