config/routes.rb
Smartstudent::Application.routes.draw do		
  root :to => "home#index"
  
  get "home/index"

  match 'home' => 'home#index', :as => :home	
  match 'register' => 'users#new',           :as => :register
  match 'login' => 'user_sessions#new',      :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions

  resources :sections do
    resources :smart_reviews do
      resources :course_reviews
      resources :professor_reviews
    end
  end

  resources :courses do
    collection do
      post :search
    end
  end

  resources :departments

  resources :professors do
    collection do
      post :search
    end
  end

  resources :users

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  has_many :sections
  has_many :smart_reviews, :through => :sections

  attr_reader :difficulty, :mood, :teaching_skills, :exams_difficulty, :helpfulness

  # HOW NOT TO DO THINGS.
  # THIS MUST BE FIXED AT ALL COSTS.
  def overall
    avg = @difficulty = @mood = @teaching_skills = 0.0
    @exams_difficulty = @helpfulness = 0.0
    count = 0 + sections.count
    count = 1 if count.zero?
    sections.each do |section|
      avg += section.professor_overall
      @difficulty += section.professor_difficulty
      @teaching_skills += section.professor_teaching
      @mood += section.professor_mood
      @exams_difficulty += section.professor_exam
      @helpfulness += section.professor_helpfulness
    end

    @difficulty /= count
    @teaching_skills /= count
    @mood /= count
    @exams_difficulty /= count
    @helpfulness /= count
    avg / count
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_filter :login_required

  # GET /professors
  # GET /professors.xml
  def index
    @professors = Professor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @professors }
    end
  end

  # GET /professors/1
  # GET /professors/1.xml
  def show
    @professor = Professor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @professor }
    end
  end

  # GET /professors/new
  # GET /professors/new.xml
  def new
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @professor }
    end
  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professors
  # POST /professors.xml
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to(@professor, :notice => 'Professor was successfully created.') }
        format.xml  { render :xml => @professor, :status => :created, :location => @professor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @professor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /professors/1
  # PUT /professors/1.xml
  def update
    @professor = Professor.find(params[:id])

    respond_to do |format|
      if @professor.update_attributes(params[:professor])
        format.html { redirect_to(@professor, :notice => 'Professor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @professor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.xml
  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to(professors_url) }
      format.xml  { head :ok }
    end
  end

  def search
    criterion = params[:criterion]
    @professors = Professor.where('lower(name) like ?', "%#{criterion.downcase}%")
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :degrees %><br />
    <%= f.text_field :degrees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/_professors.html.erb
<table>
  <tfoot>
    <tr>
      <td colspan="2"><%= "Found #{@professors.count} professors." %></td>
    </tr>
  </tfoot>
  <tbody>
<% for professor in @professors do -%>
    <tr>
      <td>
        <%= link_to professor.name, professor_path(professor) %>
      </td>
      <td>
        <% for section in professor.sections -%>
        <p><%= link_to section.course.name, section_path(section) %></p>
        <% end -%>
      </td>
    </tr>
<% end -%>
  </tbody>
<table>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render 'form' %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<h1>Listing professors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Degrees</th>
    <th>Rating</th>
    <th></th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td><%= professor.name %></td>
    <td><%= professor.description %></td>
    <td><%= professor.degrees %></td>
    <td><%= professor.overall %></td>
    <td><%= link_to 'Show', professor %></td>
  </tr>
<% end %>
</table>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render 'form' %>

<%= link_to 'Back', professors_path %>

app/views/professors/search.js.erb
$("#results").html("<%= escape_javascript(render("professors")) %>");

app/views/professors/sections.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @professor.name %>
</p>

<p>
  <b>Description:</b>
  <%= @professor.description %>
</p>

<p>
  <b>Degrees:</b>
  <%= @professor.degrees %>
</p>

<% @professor.sections do |section| %>
<p>
  <%= section.course.name %>
</p>
<% end %>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @professor.name %>
</p>
<p>
  <b>Description:</b>
  <%= @professor.description %>
</p>
<p>
  <b>Degrees:</b>
  <%= @professor.degrees %>
</p>
<div>
  <p>
    <b>Overall:</b>
    <%= @professor.overall %>
  </p>
  <p>
    <b>Difficulty:</b>
    <%= @professor.difficulty %>
  </p>
  <p>
    <b>Mood:</b>
    <%= @professor.mood %>
  </p>
  <p>
    <b>Teaching Skills:</b>
    <%= @professor.teaching_skills %>
  </p>
  <p>
    <b>Helpfulness:</b>
    <%= @professor.helpfulness %>
  </p>
  <p>
    <b>Exams Difficulty:</b>
    <%= @professor.exams_difficulty %>
  </p>
</div>
<div>
  <b>Courses:</b> List of courses taught by this professor.
<table>
  <thead>
    <tr>
      <th>
        Course Id
      </th>
      <th>
        Course name
      </th>
      <th>
        Overall Professor Rating
      </th>
    </tr>
  </thead>
  <tbody>
<% for section in @professor.sections %>
    <tr>
      <td>
        <%= "#{section.course.department.key}-#{section.course.key}" %>
      </td>
      <td>
        <%= link_to section.course.name, section_path(@professor) %>
      </td>
      <td>
        <%= section.professor_overall %>
      </td>
    <tr/>
<% end %>
  <tbody>
</table>
</div>
<% for smart_review in @professor.smart_reviews %>
<%= render :partial => 'sections/professor_review', :collection => smart_review.professor_reviews %>
<% end %>