config/routes.rb
Smartstudent::Application.routes.draw do		
  root :to => "home#index"
  
  get "home/index"

  match 'home' => 'home#index', :as => :home	
  match 'register' => 'users#new',           :as => :register
  match 'login' => 'user_sessions#new',      :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions

  resources :sections do
    resources :smart_reviews do
      resources :course_reviews
      resources :professor_reviews
    end
  end

  resources :courses do
    collection do
      post :search
    end
  end

  resources :departments

  resources :professors do
    collection do
      post :search
    end
  end

  resources :users

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :login_required

  # GET /courses
  # GET /courses.xml
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
      format.js { render :layout => false }
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end

  def search
    criterion = params[:criterion]
    if (criterion.to_i.zero?)
      @courses = Course.where('lower(name) like ?', "%#{criterion.downcase}%")
    else
      @courses = Course.where('`key` like ?', "#{criterion}%")
    end
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courses.html.erb
<table>
  <tfoot>
    <tr>
      <td colspan="3"><%= "Found #{@courses.count} courses." %></td>
    </tr>
  </tfoot>
  <tbody>
<% for course in @courses do -%>
    <tr>
      <td>
        <%= "#{course.department.key}-#{course.key}" %>
      </td>
      <td>
        <%= link_to course.name, course_path(course) %>
      </td>
      <td>
        <% for section in course.sections -%>
        <p><%= link_to section.professor.name, section_path(section) %></p>
        <% end -%>
      </td>
    </tr>
<% end -%>
  </tbody>
<table>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/_show.html.erb
<div>
  <%= show.department.key %>-<%= show.key %>
  <%= show.name %>
</div>


<% show.sections.each do |section| %>
  <p>
  <%= link_to section.professor.name, section_path(section) %>
  <%= section.course_overall %>
  </p>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>



<table>
  <tr>
    <th>Key</th>
    <th>Name</th>
    <th>Description</th>
    <th>Rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.key %></td>
    <td><%= course.name %></td>
    <td><%= course.description %></td>
    <td><%= course.overall %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/search.js.erb
$("#results").html("<%= escape_javascript(render("courses")) %>");

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @course.key %>
</p>
<p>
  <b>Name:</b>
  <%= @course.name %>
</p>
<p>
  <b>Description:</b>
  <%= @course.description %>
</p>
<div>
  <p>
    <b>Overall</b>
    <%= @course.overall %>
  </p>
  <p>
    <b>Difficulty</b>
    <%= @course.difficulty %>
  </p>
  <p>
    <b>Content</b>
    <%= @course.content %>
  </p>
  <p>
    <b>Usefulness</b>
    <%= @course.usefulness %>
  </p>
  <p>
    <b>Time Spent</b>
    <%= @course.time_spent %>
  </p>
  <p>
    <b>Recommend</b>
    <%= @course.recommend %>
  </p>
</div>
<p>
  <b>Professors:</b><br />
  <% @course.sections.each do |section| %>
    <%= link_to section.professor.name, section_path(section) %>
    <%= section.course_overall %>
    <br />
  <% end %>
</p>
<% for smart_review in @course.smart_reviews %>
<%= render :partial => 'sections/course_review', :collection => smart_review.course_reviews %>
<% end %>