config/routes.rb
Smartstudent::Application.routes.draw do		
  root :to => "home#index"
  
  get "home/index"

  match 'home' => 'home#index', :as => :home	
  match 'register' => 'users#new',           :as => :register
  match 'login' => 'user_sessions#new',      :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions

  resources :sections do
    resources :smart_reviews do
      resources :course_reviews
      resources :professor_reviews
    end
  end

  resources :courses do
    collection do
      post :search
    end
  end

  resources :departments

  resources :professors do
    collection do
      post :search
    end
  end

  resources :users

end

app/controllers/smart_reviews_controller.rb
class SmartReviewsController < ApplicationController
  before_filter :login_required

  # GET /smart_reviews
  # GET /smart_reviews.xml
  def index
    @smart_reviews = SmartReview.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @smart_reviews }
    end
  end

  # GET /smart_reviews/1
  # GET /smart_reviews/1.xml
  def show
    @smart_review = SmartReview.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @smart_review }
    end
  end

  # GET /smart_reviews/new
  # GET /smart_reviews/new.xml
  def new
    @smart_review = SmartReview.new
    @smart_review.professor_reviews.build
    @smart_review.course_reviews.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @smart_review }
    end
  end

  # GET /smart_reviews/1/edit
  def edit
    @smart_review = SmartReview.find(params[:id])
  end

  # POST /smart_reviews
  # POST /smart_reviews.xml
  def create
    @smart_review = SmartReview.new(params[:smart_review])
    @smart_review.user = current_user
    @smart_review.section_id = params[:section_id]

    respond_to do |format|
      if @smart_review.save
        format.html { redirect_to(@smart_review.section, :notice => 'Smart review was successfully created.') }
        format.xml  { render :xml => @smart_review, :status => :created, :location => @smart_review }
      else
        format.html { redirect_to(@smart_review.section) }
        format.xml  { render :xml => @smart_review.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /smart_reviews/1
  # PUT /smart_reviews/1.xml
  def update
    @smart_review = SmartReview.find(params[:id])

    respond_to do |format|
      if @smart_review.update_attributes(params[:smart_review])
        format.html { redirect_to(@smart_review, :notice => 'Smart review was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @smart_review.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /smart_reviews/1
  # DELETE /smart_reviews/1.xml
  def destroy
    @smart_review = SmartReview.find(params[:id])
    @smart_review.destroy

    respond_to do |format|
      format.html { redirect_to(smart_reviews_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/smart_reviews_helper.rb
module SmartReviewsHelper
end

app/views/smart_reviews/_course_review.html.erb
<p>
  <b>Comment:</b>
  <%= course_review.comment %>
</p>

<p>
  <b>Difficulty:</b>
  <%= course_review.difficulty %>
</p>

<p>
  <b>Usefulness:</b>
  <%= course_review.usefulness %>
</p>

<p>
  <b>Content:</b>
  <%= course_review.content %>
</p>

<p>
  <b>Time spent:</b>
  <%= course_review.time_spent %>
</p>

<p>
  <b>Recommend:</b>
  <%= course_review.recommend %>
</p>

app/views/smart_reviews/_form.html.erb
<%= form_for(@smart_review) do |f| %>
  <% if @smart_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smart_review.errors.count, "error") %> prohibited this smart_review from being saved:</h2>

      <ul>
      <% @smart_review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%#= f.text_field :user_id %>
    <%= current_user.id %>
  </div>
  <div class="field">
    <%= f.label :section_id %><br />
    <%= f.text_field :section_id %>
  </div>
  <div>
    <h2>Professor</h2>
      <% f.fields_for :professor_reviews do |fp| %>
      <div class="field">
        <%= fp.label :comment %><br />
        <%= fp.text_area :comment, :rows => 3 %>
      </div>
      <div class="field">
        <%= fp.label :difficulty %><br />
        <%= fp.text_field :difficulty %>
      </div>
      <div class="field">
        <%= fp.label :mood %><br />
        <%= fp.text_field :mood %>
      </div>
      <div class="field">
        <%= fp.label :teaching_method %><br />
        <%= fp.text_field :teaching_skills %>
      </div>
      <div class="field">
        <%= fp.label :exams_difficulty %><br />
        <%= fp.text_field :exams_difficulty %>
      </div>
      <div class="field">
        <%= fp.label :helpfulness %><br />
        <%= fp.text_field :helpfulness %>
      </div>
    <% end %>
  </div>
  <div>
    <h2>Course</h2>
    <% f.fields_for :course_reviews do |fc| %>
    <div class="field">
      <%= fc.label :comment %><br />
      <%= fc.text_area :comment, :rows => 3 %>
    </div>
    <div class="field">
      <%= fc.label :difficulty %><br />
      <%= fc.text_field :difficulty %>
    </div>
    <div class="field">
      <%= fc.label :usefulness %><br />
      <%= fc.text_field :usefulness %>
    </div>
    <div class="field">
      <%= fc.label :content %><br />
      <%= fc.text_field :content %>
    </div>
    <div class="field">
      <%= fc.label :time_spent %><br />
      <%= fc.text_field :time_spent %>
    </div>
    <div class="field">
      <%= fc.label :recommend %><br />
      <%= fc.text_field :recommend %>
    </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/smart_reviews/_professor_review.html.erb
<p>
  <b>Comment:</b>
  <%= professor_review.comment %>
</p>

<p>
  <b>Difficulty:</b>
  <%= professor_review.difficulty %>
</p>

<p>
  <b>Mood:</b>
  <%= professor_review.mood %>
</p>

<p>
  <b>Teaching method:</b>
  <%= professor_review.teaching_skills %>
</p>

<p>
  <b>Exams difficulty:</b>
  <%= professor_review.exams_difficulty %>
</p>

<p>
  <b>Helpfulness:</b>
  <%= professor_review.helpfulness %>
</p>

app/views/smart_reviews/edit.html.erb
<h1>Editing smart_review</h1>

<%= render 'form' %>

<%= link_to 'Show', @smart_review %> |
<%= link_to 'Back', smart_reviews_path %>

app/views/smart_reviews/index.html.erb
<h1>Listing smart_reviews</h1>

<table>
  <tr>
    <th>User</th>
    <th>Section</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @smart_reviews.each do |smart_review| %>
  <tr>
    <td><%= smart_review.user %></td>
    <td><%= smart_review.section %></td>
    <td><%= link_to 'Show', smart_review %></td>
    <td><%= link_to 'Edit', edit_smart_review_path(smart_review) %></td>
    <td><%= link_to 'Destroy', smart_review, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Smart review', new_smart_review_path %>

app/views/smart_reviews/new.html.erb
<h1>New smart_review</h1>

<%= render 'form' %>

<%= link_to 'Back', smart_reviews_path %>

app/views/smart_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @smart_review.user %>
</p>

<p>
  <b>Section:</b>
  <%= @smart_review.section %>
</p>

<div>
  <h2>Professor</h2>
  <%= render :partial => 'professor_review', :object => @smart_review.professor_reviews.first %>
</div>

<div>
  <h2>Course</h2>
  <%= render :partial => 'course_review', :object=> @smart_review.course_reviews.first %>
</div>

<%= link_to 'Edit', edit_smart_review_path(@smart_review) %> |
<%= link_to 'Back', smart_reviews_path %>